#!/bin/csh -f 

# USERS MUST CHANGE THESE !!!!!!
set SWIFT_DIR=~/Work/SCATR_generic
set FORTRAN=gfortran
#set FFLAGS='-c -O3 -static -no-prec-div -xP'
set FFLAGS='-c -O3 -funroll-all-loops'
#set FFLAGS='-c -fast'
#set FFLAGS='-O3 +Onolimit +Oall +Odataprefetch +Ovectorize +Ocache_pad_common -c'
set PRECOMP=cpp
set CPPFLAGS='-U_OPEN_POSITION'
#set CPPFLAGS='-D_OPEN_POSITION -D_RECUR_SUB'

# To Profile the code:
#set FFLAGS='-G -c'

if (`ls *.F | wc -l` != 0 ) then
    echo Doing precompiler
    foreach file (*.F)
        echo $file | set file2=`awk -F"." '{print$1}'`
        echo $file2
        $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
     end
else  
    echo No need to precompile
endif

echo Doing Fortran
foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file2
    $FORTRAN $FFLAGS "$file2".f
    ar vr $SWIFT_DIR/libscatr.a  "$file2".o
end

rm *.o
rm *CPP.f
echo Done directory $PWD 
