#!/bin/csh -f

# USERS MUST CHANGE THESE !!!!!!
set SWIFT_DIR=/users/nathankaib/Work/SCATR_generic
set FORTRAN='gfortran'
#set FFLAGS='-rcd -unroll -fno-alias -ipo -static'
#set FFLAGS='-O3 +Onolimit +Oall +Odataprefetch +Ovectorize +Ocache_pad_common'
#set FFLAGS='-O3 -static -fast -no-prec-div'
set FFLAGS='-O3 -funroll-all-loops'

# To Profile the code:
#set FFLAGS='-G -c'

foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file2
    $FORTRAN $FFLAGS "$file2".f -o "$file2"  -L/users/nathankaib/Work/SCATR_generic -lscatr
end

rm *.o
echo Done directory $PWD 

